{
    'name': 'Theme Darko',
    'version': '17.0.1.0.0',
    'category': 'Theme/eCommerce',
    'summary': 'Attractive and unique front-end theme for eCommerce websites',
    'description': 'Attractive and unique front-end theme for eCommerce websites',
    'author': 'FG',
    'company': 'Cybrosys Techno Solutions',
    'maintainer': 'Cybrosys Techno Solutions',
    'website': "https://www.cybrosys.com",
    'depends': ['web', 'website', 'website_mass_mailing', 'website_sale_wishlist'],
    'data': [
        'data/darko_configuration_data.xml',
        'data/theme_data.xml',
        'security/ir.model.access.csv',
        'views/darko_configuration_views.xml',
        'views/snippets/index/most_popular_templates.xml',
        'views/snippets/index/banner_templates.xml',
        'views/snippets/index/offer_templates.xml',
        'views/snippets/index/features_templates.xml',
        'views/snippets/index/features_templates_2.xml',
        'views/snippets/index/parallax_card_templates.xml',
        'views/snippets/index/sticky_onScroll_templates.xml',
        'views/snippets/index/sticky_feature_img_templates.xml',
        'views/snippets/index/stacked_cards_templates.xml',
        'views/snippets/index/carousal_cards_templates.xml',
        'views/snippets/index/continues_carousal_cards_templates.xml',
        'views/snippets/index/journals_templates.xml',
        'views/snippets/index/follow_us_templates.xml',
        'views/snippets/about_us/about_us_templates.xml',
        'views/snippets/index/featured_products_templates.xml',
        'views/snippets/index/trending_templates.xml',
        'views/snippets/index/type_effect_title_template.xml',
        'views/snippets/index/magical_hover_templates.xml',
        'views/snippets/index/expandable_cards_templates.xml',
        'views/snippets/index/banner_slider_templates.xml',
        'views/snippets/index/magical_text_effect_templates.xml',
        'views/snippets/index/glowing_blob_templates.xml',
        'views/snippets/index/video_onScroll_templates.xml',
        'views/megamenu_template.xml',
        'views/footer_templates.xml',
        'views/header_templates.xml',
        'views/contact_us_templates.xml',
        'views/cart_templates.xml',
        'views/product_templates.xml',
        'views/products_templates.xml',
        'views/layout_templates.xml',

    ],
    'assets': {
        'web._assets_primary_variables': [
            "theme_darko/static/src/scss/primary_variables.scss",
        ],
        'web.assets_frontend': [
            'theme_darko/static/src/css/font-awesome.min.css',
            'theme_darko/static/src/scss/_variables.scss',
            'theme_darko/static/src/scss/_normalize.scss',
            'theme_darko/static/src/scss/_typography.scss',
            'theme_darko/static/src/scss/_common.scss',
            'theme_darko/static/src/scss/components/_buttons.scss',
            'theme_darko/static/src/scss/layout/_header.scss',
            'theme_darko/static/src/scss/layout/_footer.scss',
            'theme_darko/static/src/scss/layout/_navigation.scss',
            'theme_darko/static/src/scss/components/_banner.scss',
            'theme_darko/static/src/scss/components/_product.scss',
            'theme_darko/static/src/scss/components/_animation.scss',
            'theme_darko/static/src/scss/pages/home/_offers.scss',
            'theme_darko/static/src/scss/pages/home/_features.scss',
            'theme_darko/static/src/scss/pages/home/_features_2.scss',
            'theme_darko/static/src/scss/pages/home/_sticky-onScroll.scss',
            'theme_darko/static/src/scss/pages/home/_sticky-feature-img.scss',
            'theme_darko/static/src/scss/pages/home/_stacked-cards.scss',
            'theme_darko/static/src/scss/pages/home/_continues-carousal-cards.scss',
            'theme_darko/static/src/scss/pages/home/_parallax-card.scss',
            'theme_darko/static/src/scss/pages/home/_type_effect.scss',
            'theme_darko/static/src/scss/pages/odoo-erp/s_tabs.scss',
            'theme_darko/static/src/scss/pages/odoo-erp/s_faq_collapse.scss',
            'theme_darko/static/src/scss/pages/home/_journal.scss',
            'theme_darko/static/src/scss/pages/home/_trending.scss',
            'theme_darko/static/src/scss/pages/home/_follow-us.scss',
            'theme_darko/static/src/scss/pages/home/_most-popular.scss',
            'theme_darko/static/src/scss/pages/home/_magical_hover_cards.scss',
            'theme_darko/static/src/scss/pages/home/_expandable_cards.scss',
            'theme_darko/static/src/scss/pages/home/_banner_slider.scss',
            'theme_darko/static/src/scss/pages/home/_magical_text_effect.scss',
            'theme_darko/static/src/scss/pages/home/_glowing_blob_effect.scss',
            'theme_darko/static/src/scss/pages/home/_video_onScroll.scss',
            'theme_darko/static/src/scss/pages/_maincontents.scss',
            'theme_darko/static/src/scss/pages/_product.scss',
            'theme_darko/static/src/scss/pages/_about.scss',
            'theme_darko/static/src/scss/pages/_preview.scss',
            'theme_darko/static/src/scss/pages/_contact.scss',
            'theme_darko/static/src/scss/pages/_cart.scss',
            'theme_darko/static/src/js/most_popular.js',
            'theme_darko/static/src/js/featured_product.js',
            'theme_darko/static/src/js/trending.js',
            'theme_darko/static/src/js/parallax-effect.js',
            'theme_darko/static/src/js/type_effect.js',
            'theme_darko/static/src/js/continues_carousal_cards.js',
            'theme_darko/static/src/js/magical_hover_effect.js',
            'theme_darko/static/src/js/magical_text_effect.js',
            'theme_darko/static/src/js/glowing_blob_effect.js',
            'theme_darko/static/src/js/expandable_cards.js',
            'theme_darko/static/src/js/banner_slider.js',
            'theme_darko/static/src/js/video_onScroll.js',
            'theme_darko/static/src/js/navbar_background.js',
            'theme_darko/static/src/js/navbar_background.js',
            'theme_darko/static/src/js/sticky_feature_img.js',
        ],
    },
    'images': [
        'static/description/banner.png',
        'static/description/theme_screenshot.png',
    ],
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
