version: '3.8'
services:
  odoo:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: start  
    depends_on:
      - db
    links:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ../extra-addons:/mnt/extra-addons
      - ../resources/odoo-codespace.conf:/etc/odoo/odoo.conf

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: