
name: Delete Odoo

on:
  workflow_dispatch:
    inputs:
      target-env:
        required: true
        type: string
      github_sha:
        required: true
        type: string
      snapshot:
        default: false
        type: boolean

env:
  service_name: "odoo"
  service_version: "17.0"

jobs:
    delete_cluster:
        runs-on: ubuntu-latest
        steps:
            
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Clone Infrastructure Repo
              run: git clone https://github.com/ashkan-farivarmoheb/odoo-infra.git

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: ${{ secrets.AWS_REGION }}
            - name: Variables
              id: vars
              uses: actions/github-script@v3
              with:
                script: |
                  const ecr_repository = `${process.env.service_name}-${process.env.service_version}`;
                  core.exportVariable('ecr_repository', ecr_repository);

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Set ecr_image_tag
              id: set-ecr-image-tag
              run: |
                if [[ "${{ inputs.snapshot }}" == "true" ]]; then
                    ecr_image_tag="snapshot-${{ inputs.github_sha }}"
                else
                    ecr_image_tag="develop-${{ inputs.github_sha }}"
                fi
                echo "ecr_image_tag=$ecr_image_tag" >> "$GITHUB_ENV"

            - name: Set up Terraform
              uses: hashicorp/setup-terraform@v1
              with:
                terraform_version: 1.1.0  # Specify the Terraform version to use
        
            - name: Initialize Terraform
              run: terraform init -backend-config=hcl/backend_${{ inputs.target-env }}.hcl
              working-directory: odoo-infra/cd/${{ env.ecr_repository }}/infrastructure
              
            - name: Validate Terraform configuration
              run: terraform validate
              working-directory: odoo-infra/cd/${{ env.ecr_repository }}/infrastructure
              
            - name: Plan Terraform changes
              run: terraform plan -var-file=tfvars/${{ inputs.target-env }}.auto.tfvars -var="tag=${{ env.ecr_image_tag }}" -var="new_relic_license_key=${{ env.new_relic_license_key }}"
              working-directory: odoo-infra/cd/${{ env.ecr_repository }}/infrastructure

            - name: Destroy Terraform changes
              run: terraform destroy -auto-approve -var-file=tfvars/${{ inputs.target-env }}.auto.tfvars -var="tag=${{ env.ecr_image_tag }}" -var="new_relic_license_key=${{ env.new_relic_license_key }}"
              working-directory: odoo-infra/cd/${{ env.ecr_repository }}/infrastructure